execute_sql_file:
  stage: execute
  image: postgres:14-alpine
  
  # Only run this job when SQL_FILE is provided
  rules:
    - if: $SQL_FILE
      when: always
    - when: never
  
  script:
    # Run SQL file using psql
    - PGPASSWORD=$DB_PASSWORD psql -U $DB_USERNAME -d $DB_NAME -h $DB_HOST -p $DB_PORT -f $SQL_FILE
    